version: "3.2"

services:
  twitch-notifier:
    image: quay.io/satont/twitch-notifier
    restart: always
    ports:
      - 3000:3000
    env_file:
      - ./.env
  db:
    image: postgres:13
    restart: always
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all
    environment:
      POSTGRES_USER: notifier
      POSTGRES_PASSWORD: notifier
      POSTGRES_DB: notifier
