name: Docker Image CI - latest

on:
  push:
    branches:
      - master

jobs:
  docker:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-docker]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build & Push to Docker Hub
        uses: opspresso/action-docker@v0.2.1
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          REGISTRY: docker.pkg.github.com
          IMAGE_NAME: "satont/twitch-notifier"
          TAG_NAME: master:latest
      - name: Deploy To CapRover
        uses: floms/action-caprover@v1
        with:
          host: ${{ secrets.CAPPROVER_DOMAIN }}
          password: ${{ secrets.CAPROVER_PASSWORD }}
          app: notifier
          image: docker.pkg.github.com/satont/twitch-notifier/master
